interface PaytabsResponse {
    [key: number]: {
        status: string;
        message: string;
    }
}

export const paytabsResponseCodes: PaytabsResponse = {
    0: { status: 'A', message: 'Authorised' },
    1: { status: 'E', message: 'Authentication Failed' },
    2: { status: 'E', message: 'Invalid Request' },
    3: { status: 'E', message: 'Invalid Profile ID' },
    4: { status: 'E', message: 'Duplicate Request' },
    5: { status: 'E', message: 'Request Limit Exceeded' },
    100: { status: 'E', message: 'Transaction Cost or Currency not valid' },
    101: { status: 'E', message: 'Cart ID not valid' },
    102: { status: 'E', message: 'Description not valid' },
    103: { status: 'E', message: 'Name not valid' },
    104: { status: 'E', message: 'Address not valid' },
    105: { status: 'E', message: 'Country not valid' },
    106: { status: 'E', message: 'Email not valid' },
    107: { status: 'E', message: 'Phone number not valid' },
    108: { status: 'E', message: 'IP Address not valid' },
    109: { status: 'E', message: 'Invalid transaction mode' },
    110: { status: 'E', message: 'Invalid transaction type' },
    111: { status: 'E', message: 'Invalid transaction class' },
    112: { status: 'E', message: 'Method/ Class / Currency combination not supported' },
    113: { status: 'E', message: 'Invalid transaction reference' },
    114: { status: 'E', message: 'Amount differs from original' },
    115: { status: 'E', message: 'Original transaction not authorised' },
    116: { status: 'E', message: 'Original transaction already voided' },
    117: { status: 'E', message: 'Original transaction mismatch' },
    118: { status: 'E', message: 'Amount greater than available balance' },
    119: { status: 'E', message: 'Original transaction can not be voided' },
    120: { status: 'E', message: 'Previous transaction is on hold' },
    121: { status: 'E', message: 'Transaction mode differs from original' },
    122: { status: 'D', message: 'Continuous authority not available on referenced transaction' },
    123: { status: 'E', message: 'City not valid' },
    200: { status: 'E', message: 'Invalid card number' },
    201: { status: 'E', message: 'Invalid card expiry date' },
    202: { status: 'E', message: 'Invalid card security code(CVV)' },
    203: { status: 'E', message: 'Invalid account' },
    204: { status: 'E', message: 'Previous transaction in use' },
    205: { status: 'E', message: 'Invalid payment method' },
    206: { status: 'D', message: 'Currency mismatch' },
    207: { status: 'E', message: 'Invalid terminal' },
    208: { status: 'E', message: 'Invalid return url' },
    209: { status: 'E', message: 'Invalid merchant token' },
    211: { status: 'E', message: 'Profile mismatch' },
    212: { status: 'E', message: 'Permission Denied' },
    213: { status: 'D', message: 'Card does not match filter' },
    214: { status: 'E', message: 'Terminal invalid request' },
    215: { status: 'E', message: 'Terminal unable to process request' },
    216: { status: 'E', message: 'Invalid refund mode' },
    300: { status: 'D', message: 'Not authorised' },
    301: { status: 'D', message: 'Card expiry date required' },
    302: { status: 'D', message: 'Card expired / incorrect expiry date' },
    303: { status: 'D', message: 'Card is not ATM use only' },
    304: { status: 'D', message: 'Card security code(CVV) required' },
    305: { status: 'D', message: 'Card security code(CVV) mismatch' },
    306: { status: 'D', message: 'Address verification(AVS) mismatch' },
    307: { status: 'D', message: 'Card security code(CVV) and address(AVS) mismatch' },
    308: { status: 'D', message: 'Card is not enabled for e-commerce' },
    309: { status: 'D', message: '3DSecure authentication not available for this card' },
    310: { status: 'D', message: '3DSecure authentication rejected' },
    311: { status: 'D', message: 'Card cancelled' },
    312: { status: 'D', message: 'No / invalid account' },
    313: { status: 'D', message: 'Transaction not permitted by issuer' },
    314: { status: 'D', message: 'Not authorised' },
    315: { status: 'D', message: 'Not authorised' },
    316: { status: 'D', message: 'Insufficient funds' },
    317: { status: 'D', message: 'Blocked by acquirer' },
    318: { status: 'X', message: 'Authorisation expired' },
    319: { status: 'D', message: 'Unable to void' },
    320: { status: 'D', message: 'Unable to refund' },
    321: { status: 'C', message: 'Cancelled' },
    322: { status: 'D', message: 'Not supported by acquirer' },
    323: { status: 'D', message: 'Card limits exceeded' },
    324: { status: 'D', message: 'Terminal limits exceeded' },
    325: { status: 'D', message: 'Merchant limits exceeded' },
    326: { status: 'D', message: 'Account limits exceeded' },
    327: { status: 'D', message: 'OTP timeout' },
    328: { status: 'D', message: 'Refund request not approved' },
    329: { status: 'D', message: 'Declined by card issuer' },
    330: { status: 'D', message: 'Unable to capture' },
    331: { status: 'D', message: 'Minimum financed amount violation' },
    332: { status: 'D', message: 'Wallet customer not found' },
    333: { status: 'D', message: 'OTP is invalid' },
    334: { status: 'D', message: 'Unable to retrieve details from processor' },
    335: { status: 'D', message: 'Transaction type not supported by acquirer' },
    336: { status: 'D', message: 'Trading suspended' },
    337: { status: 'D', message: 'Refund declined by acquirer' },
    338: { status: 'D', message: 'Authentication not available' },
    339: { status: 'D', message: 'OTP attempts exceeded' },
    340: { status: 'D', message: 'Not registered for OTP' },
    341: { status: 'D', message: 'Transaction time exceeded' },
    342: { status: 'D', message: 'Refund balance exceeded' },
    343: { status: 'D', message: 'Declined by acquirer' },
    344: { status: 'D', message: 'Acquirer is unable to process this request' },
    345: { status: 'D', message: '3DSecure authentication not completed' },
    346: { status: 'D', message: 'Issuer unable to process 3DSecure' },
    347: { status: 'D', message: 'Incorrect PIN' },
    348: { status: 'D', message: 'Allowable PIN tries exceeded' },
    349: { status: 'E', message: 'Invalid merchant account' },
    350: { status: 'D', message: 'Invalid tenure' },
    351: { status: 'D', message: 'Invalid downpayment' },
    400: { status: 'E', message: 'Internal system error' },
    401: { status: 'E', message: 'No response' },
    402: { status: 'E', message: 'Error connecting to service provider' },
    500: { status: 'D', message: 'Declined' },
    501: { status: 'D', message: 'Declined' },
    502: { status: 'D', message: 'Declined' },
    503: { status: 'D', message: 'Declined' },
    504: { status: 'D', message: 'Declined' },
    600: { status: 'P', message: 'Pending' },
    601: { status: 'H', message: 'On Hold' }
}